### ISSUE TITLE
Help needed in configuring Prometheus for Cortex

### ISSUE THREAD

**Issue by kavin-kr** [blind-oracle/cortex-tenant#20]
Hi all,

I need to push metrics from Prometheus to Mimir along with tenant id based on deployed pod/resource label `workspaceId`.
```sh
$ kubectl get pod/deployment-afb57b22d92b4d46bdd201e437e23d50-76f7f67f45-m8wg6 -n 2ee8544f99ba4cedaf627e4bccaa7abe -o jsonpath='{$.metadata.labels}' | jq
{
  "app.kubernetes.io/name": "vault",
  "deploymentId": "afb57b22d92b4d46bdd201e437e23d50",
  "pod-template-hash": "76f7f67f45",
  "region": "eb1ce3b00d024e27ad620ee8e74ed691",
  "workspaceId": "2ee8544f99ba4cedaf627e4bccaa7abe"
}
```
\
So Deployed cortex-tenant using this below config,
```yaml
# only changed values are shown
data:
  cortex-tenant.yml: |
    tenant:
      # cusom label name to be used as tenant information
      label: workspaceId
```
\
While deploying prometheus/kube-prometheus-stack chart, tried using the below config, but still couldn't able to get those labels in metrics.
```yaml
# only corresponding values are shown
kube-state-metrics:
  metricLabelsAllowlist: 
    - pods=[workspaceId]
```
\
How to inject a specific pod label in prometheus time series, so that it can be used in cortex-tenant?
Could someone help configuring Prometheus for this use case?
