### ISSUE TITLE
HTTP 405 error

### ISSUE THREAD

**Issue by SangjunPark54** [blind-oracle/cortex-tenant#28]
prometheus-server ts=2023-05-17T07:33:56.434Z caller=dedupe.go:112 component=remote level=error remote_name=24a04d url=http://a3.ap.elb.amazonaws.com:8080/push msg="non-recoverable error" count=10 err="server returned HTTP status 405 Method Not Allowed: "

prometheus cm -
```
    remote_write:
    - url: "http://a3.ap.elb.amazonaws.com:8080/push"
    scrape_configs:
    - job_name: tenant-job
      scrape_interval: 60s
      static_configs:
      - targets:
          - localhost:9090
        labels:
          tenant: foobar
```
tenant-cortex cm

```
apiVersion: v1
    log_level: debug
    # HTTP request timeout
    timeout: 10s
    # Timeout to wait on shutdown to allow load balancers detect that we're going away.
    # During this period after the shutdown command the /alive endpoint will reply with HTTP 503.
    # Set to 0s to disable.
    timeout_shutdown: 10s
    # Max number of parallel incoming HTTP requests to handle
    concurrency: 1000
    # Whether to forward metrics metadata from Prometheus to Cortex
    # Since metadata requests have no timeseries in them - we cannot divide them into tenants
    # So the metadata requests will be sent to the default tenant only, if one is not defined - they will be dropped
    metadata: false
    tenant:
      # Which label to look for the tenant information
      label: tenant
      # Optional hard-coded prefix with delimeter for all tenant values.
      # Delimeters allowed for use:
      # https://grafana.com/docs/mimir/latest/configure/about-tenant-ids/
      prefix: ""
      # Whether to remove the tenant label from the request
      label_remove: true
      # To which header to add the tenant ID
      header: X-Scope-OrgID
      # Which tenant ID to use if the label is missing in any of the timeseries
      # If this is not set or empty then the write request with missing tenant label
      # will be rejected with HTTP code 400
      default: cortex-tenant-default
      # Enable if you want all metrics from Prometheus to be accepted with a 204 HTTP code
      # regardless of the response from Cortex. This can lose metrics if Cortex is
      # throwing rejections.
```
