### ISSUE TITLE
Suggestion: Create a helm chart

### ISSUE THREAD

**Issue by WhiteDiamondz** [blind-oracle/cortex-tenant#32]
Good afternoon !
I find your project very useful and wanted to implement it since I currently have the use case with mimir. However, I noticed that there are only the manifest files for the k8s resources and I couldn't help but think that an helm chart would allow more people to easily set up and customize your solution ! 
It is posible to [publish one and claim ownership on Artifact Hub](https://artifacthub.io/docs/topics/repositories/helm-charts/) 
If you are interested, I could create a merge request with a basic helm chart with templated manifests, let me know !

**Comment by blind-oracle** [comment]
Sure, please do, i don't use it but if it will be useful - why not

**Comment by WhiteDiamondz** [comment]
Hey again !

I've started working the helm chart implementation but I encountered a difficulty. For security reasons, I pass authentification secrets to the pod through environment variables. However, the code is not configured to replace an environment variable in the config with it's value (https://github.com/blind-oracle/cortex-tenant/blob/1166821fbbd58b399c335289a994047552323def/config.go#L84).

To better illustrate what I mean, my config file that looks like this: 
```
[...]
    auth:
      egress:
        username: ${MIMIR_CLIENT_ID}
        password: ${MIMIR_CLIENT_SECRET}
[...]
```
Any chance a new function like `configEnvParse()` or a new section in `configParse()` could be added to replace the variables with their values before loading it?

**Comment by marcinfigiel** [comment]
The configuration is loaded from a config file, right? You can add a `ConfigMap` to the chart templates, mount it to the pod under the config file path and fill it with values from the values.yaml file. 

`ConfigMap` template:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cortex-tenant-config
  namespace: {{ .Release.Namespace }}
data:
  "cortex-tenant.yml": |
{{- with .Values.config -}}
  {{- toYaml . | nindent 4 }}
{{- end -}}
```

Deployment `volumes` section:
```yaml
      volumes:
        {{- toYaml .Values.volumes | default "" | nindent 8 }}
```

Deployment spec `volumeMounts` section:
```yaml
          volumeMounts:
            {{- toYaml .Values.volumeMounts | default "" | nindent 12 }}
```

Values file:
```yaml
volumes:
  - name: cortex-tenant-config
    configMap:
      name: cortex-tenant-config

volumeMounts:
  - name: cortex-tenant-config
    mountPath: /data/cortex-tenant.yml
    subPath: cortex-tenant.yml

config:
    # Where to listen for incoming write requests from Prometheus
  listen: 0.0.0.0:8080
  # Log level
  log_level: error
...
```

The `config` section is the content of the configuration file. 

What do you thinkg about this approach?

**Comment by WhiteDiamondz** [comment]
Yes, this is already what I am doing. 

However, I wish to use a secret Kubernetes secret to isolate sensible info (in this case the login/password for the authentication). This implies referencing the file that contains these secrets in the configuration or to pass them through environment variables.

From what I understand, your solution would require the such sensible information to be in plain text in your `values.yaml` file with the rest of the configuration wouldn't it?

Instead of having a commited `values.yaml` file that looks like:
```
config:
  auth:
    username: my-username
    password: p@ssword!
```

I want it to be like the the following with the variables correctly used once the config is mounted to the pod:
```
config:
  auth:
    username: "${MIMIR_CLIENT_ID}"
    password: "${MIMIR_CLIENT_SECRET}"
```
